name: Upload Provided Binary

on:
  push:
    branches:
      -main # Trigger when pushing to main branch
  workflow_dispatch: # Allows maual trigger

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v3

     - name: Download Professor's Binary
       run: |
         wget -O symptom_checker/binary.tar.gz "https://github.com/24W-GBAC/commr/releases/download/v3/x86_64-unknown-linux-musl.tar.gz"
         tar -xzf symptom_checker/binary.tar.gz -C symptom_checker
         mv symptom_checker/* symptom_checker/professor-binary

     - name: Upload Provided Binary
       uses: actions/upload-artifact@v3
       with:
         name: SymptoRust-Binary
         path: symptom_checker/professor-binary # Change this to the correct path

     - name: Create Github Release
       uses: softprops/action-gh-release@v1
       with:
         files: symptom_checker/professor-binary # Change this to the correct path
         tag_name: v1.0
         name: SymptomRust v1.0
         body: |
           This is the first release of SymptoRust.
            - Provided by Professor.
            - Download the binaary and use it directly.
env:
 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

